name: CI/CD - Flag Explorer App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend Build & Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List Directory Structure
        run: |
          pwd
          ls -la  

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore FlagExplorer.sln
        
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build Solution
        run: dotnet build FlagExplorer.sln --no-restore --configuration Release

      - name: Run Backend Tests
        run: dotnet test tests/FlagExplorer.Tests/FlagExplorer.Tests.csproj --no-build --verbosity normal --collect:"XPlat Code Coverage"

      - name: Publish API for Deployment
        run: dotnet publish src/FlagExplorer.Api/FlagExplorer.Api.csproj -c Release -o backend-publish

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: backend-publish
          retention-days: 5
          if-no-files-found: error
          compression-level: 9

  frontend:
    name: Frontend Build & Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Frontend Dependencies
        run: npm ci

      - name: Run Frontend Tests
        run: npm test -- --watchAll=false --coverage
        env:
          CI: true

      - name: Build Frontend
        run: npm run build
        env:
          CI: true
         
      - name: List Build Directory
        run: ls -la dist || ls -la build    

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: |
            frontend/dist
            frontend/build
          retention-days: 5
          if-no-files-found: error
          compression-level: 9
