name: CI/CD - Flag Explorer App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend Build & Test
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Updated to latest version

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4  # Updated to latest version
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore FlagExplorer.sln
        
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build Solution
        run: dotnet build FlagExplorer.sln --no-restore --configuration Release

      - name: Run Backend Tests
        run: dotnet test tests/FlagExplorer.Tests/FlagExplorer.Tests.csproj --no-build --verbosity normal --collect:"XPlat Code Coverage"

      - name: Publish API for Deployment
        run: dotnet publish src/FlagExplorer.Api/FlagExplorer.Api.csproj -c Release -o backend-publish

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: backend
          path: backend-publish
          retention-days: 5  # Added retention period

  frontend:
    name: Frontend Build & Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Updated to latest version

      - name: Setup Node.js
        uses: actions/setup-node@v4  # Updated to latest version
        with:
          node-version: 20
          cache: 'npm'  # Added caching
          cache-dependency-path: frontend/package-lock.json

      - name: Install Frontend Dependencies
        run: npm ci  # Changed to ci for cleaner installs

      - name: Run Frontend Tests
        run: npm test -- --watchAll=false --coverage
        env:
          CI: true  # Added CI environment variable

      - name: Build Frontend
        run: npm run build
        env:
          CI: true

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: frontend
          path: frontend/dist
          retention-days: 5  # Added retention period
